import type { Metadata } from 'next'
import { PageHeader } from '@/components/site/page-header'
import { AplusShowcase } from '@/components/site/aplus-showcase'
import { VideoShowcase } from '@/components/site/video-showcase'
import { PitchBrands } from '@/components/site/pitch-brands'
import { GeneratedMarquee } from '@/components/site/generated-marquee'
import { RealWork } from '@/components/site/real-work'
import { CTA } from '@/components/site/cta'

export const metadata: Metadata = {
  title: 'Showcase',
  description:
    'Real A+ content, ad creative, product photography, and UGC video. Every asset generated inside ArrowLabs from a single product link.',
  alternates: { canonical: '/showcase' },
  openGraph: {
    title: 'Showcase · ArrowLabs',
    description: 'Real A+ content, ad creative, product photography, and UGC video, generated on demand.',
    url: '/showcase',
    images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: 'ArrowLabs' }],
  },
  twitter: { images: ['/opengraph-image'] },
}

export default function ShowcasePage() {
  return (
    <>
      <PageHeader
        eyebrow="§ Showcase · generated by ThreeArrow AI"
        title="Real output,"
        accent="rendered on demand."
        description="No stock, no photographer, no reshoots. Every image and video below was generated inside ArrowLabs. This is the actual quality your store gets from day one."
      />
      <AplusShowcase />
      <VideoShowcase />
      <PitchBrands />
      <GeneratedMarquee />
      <RealWork />
      <CTA />
    </>
  )
}
