// Central image registry for ArrowLabs marketing site
// All URLs are OSS-hosted and stable

// Premium in-house visuals generated with gpt-image-2 (see scripts/gen_marketing_images.mjs)
export const MARKETING = {
  heroStudio: '/marketing/premium/model-athleisure.png',
  aplusLifestyle: '/marketing/premium/model-skincare.png',
  amazonListing: '/marketing/premium/beauty-flatlay.png',
  adCreative: '/marketing/ad-creative.png',
  ugcCreator: '/marketing/premium/onmodel-accessory.png',
  dashboard: '/marketing/dashboard.png',
} as const

export const IMAGES = {
  // Skincare / product photography (for ListingLab + PhotoLab)
  skincare: [
    '/marketing/aplus-lifestyle.png',
    'https://sfile.chatglm.cn/images-ppt/294213f8e821.jpg',
    'https://sfile.chatglm.cn/images-ppt/01fa398cc69c.jpg',
    'https://sfile.chatglm.cn/images-ppt/b755f16cfad3.jpg',
    'https://sfile.chatglm.cn/images-ppt/ef3d12d4cc51.jpg',
  ],
  // Ad creatives (for AngleLab)
  adcreative: [
    '/marketing/ad-creative.png',
    'https://sfile.chatglm.cn/images-ppt/adfa00e8354b.png',
    'https://sfile.chatglm.cn/images-ppt/276c69b02bdd.jpg',
    'https://sfile.chatglm.cn/images-ppt/0768edd984ab.jpg',
    'https://sfile.chatglm.cn/images-ppt/cd103c198556.jpg',
  ],
  // UGC video creators (for VideoLab)
  ugc: [
    '/marketing/ugc-creator.png',
    'https://sfile.chatglm.cn/images-ppt/3d9597667d6a.jpg',
    'https://sfile.chatglm.cn/images-ppt/413fa2c1a053.jpg',
    'https://sfile.chatglm.cn/images-ppt/93d841c37e75.jpg',
    'https://sfile.chatglm.cn/images-ppt/ec0a6e2da0a8.jpg',
  ],
  // Dashboard mockups (for Workspace section)
  dashboard: [
    '/marketing/dashboard.png',
    'https://sfile.chatglm.cn/images-ppt/f548595490da.jpg',
    'https://sfile.chatglm.cn/images-ppt/eb3861a6a063.jpg',
    'https://sfile.chatglm.cn/images-ppt/d71b63b34ec1.jpg',
    'https://sfile.chatglm.cn/images-ppt/b20b8a24c84b.jpg',
  ],
  // Amazon listing examples
  amazon: [
    '/marketing/amazon-listing.png',
    'https://sfile.chatglm.cn/images-ppt/5f6f01f20375.jpg',
    'https://sfile.chatglm.cn/images-ppt/d71a42bbc527.jpg',
    'https://sfile.chatglm.cn/images-ppt/6921845c008d.jpg',
    'https://sfile.chatglm.cn/images-ppt/2ceb0b907f0c.jpg',
  ],
  // Customer avatars
  avatars: [
    'https://sfile.chatglm.cn/images-ppt/1545597d0cf6.jpg',
    'https://sfile.chatglm.cn/images-ppt/c0e63bb3e892.jpg',
    'https://sfile.chatglm.cn/images-ppt/346f8e690b8c.jpg',
    'https://sfile.chatglm.cn/images-ppt/22cf8c1068b9.jpg',
    'https://sfile.chatglm.cn/images-ppt/409fd50842b9.jpg',
    'https://sfile.chatglm.cn/images-ppt/4cbec5251dc5.jpeg',
    'https://sfile.chatglm.cn/images-ppt/d7cbd1a0e369.jpg',
    'https://sfile.chatglm.cn/images-ppt/7d27f5fefffd.jpg',
  ],
} as const

// Brand constants
export const BRAND = {
  name: 'ArrowLabs',
  domain: 'ArrowLabs.ai',
  tagline: 'The Creative Operating System for Commerce',
  description:
    'ArrowLabs is the creative studio for modern commerce. Listings, ads, photos, and video, generated by AI, directed by you.',

  year: new Date().getFullYear(),
}
