// Showcase media registry - single source of truth for the marketing gallery.
// Two kinds of media:
//   1. `generated` - premium creatives produced in-house with gpt-image-2
//      (scripts/gen_marketing_images.mjs + gen_brand_images.mjs)
//   2. `caseStudies` - real D2C storefronts built with this stack
//      (assets curated from live catalogs, web-optimized into public/showcase/)

export type CaseStudy = {
  brand: string
  category: string
  blurb: string
  cover: string
  gallery: string[]
}

// Real D2C brands whose full catalogs were produced with ArrowLabs' prompt
// system - the proof that the output holds up across an entire storefront.
export const CASE_STUDIES: CaseStudy[] = [
  {
    brand: 'House of Tarasha',
    category: 'Handcrafted home & decor · D2C',
    blurb:
      'Editorial storytelling for artisan homeware - craft heritage, warm interiors, and collection imagery that carries the brand across every surface of the storefront.',
    cover: '/showcase/hot/hero-home.jpg',
    gallery: [
      '/showcase/hot/hero-home.jpg',
      '/showcase/hot/craft.jpg',
      '/showcase/hot/brass-atelier.jpg',
      '/showcase/hot/living-room.jpg',
      '/showcase/hot/artisan.jpg',
      '/showcase/hot/gift-room.jpg',
    ],
  },
]

// Flat list of generated creatives for the animated scrolling gallery.
export const GENERATED_GALLERY = [
  '/marketing/premium/model-skincare.png',
  '/marketing/premium/beauty-flatlay.png',
  '/marketing/premium/model-athleisure.png',
  '/marketing/premium/onmodel-accessory.png',
  '/marketing/premium/lifestyle-kitchen.png',
  '/marketing/premium/lifestyle-desk.png',
  '/marketing/premium/home-editorial.png',
  '/marketing/premium/ugc-creator.png',
  '/marketing/brands/cerave.png',
  '/marketing/brands/owala.png',
  '/marketing/brands/sony.png',
  '/marketing/brands/prime.png',
  '/marketing/brands/gymshark.png',
  '/marketing/brands/ninja.png',
  '/marketing/aplus-lifestyle.png',
  '/marketing/amazon-listing.png',
]

// Rising D2C brands - pitch targets. Every asset generated by ArrowLabs.
export type PitchBrand = { name: string; key: string; category: string; hero: string; life: string; video?: string }
export const PITCH_BRANDS: PitchBrand[] = [
  { name: 'Peeko', key: 'peeko', category: 'Baby & kids wear', hero: '/pitch/peeko-hero.png', life: '/pitch/peeko-life.png' },
  { name: 'Minimalist', key: 'minimalist', category: 'Skincare', hero: '/pitch/minimalist-hero.png', life: '/pitch/minimalist-life.png', video: '/pitch/ugc-skincare.mp4' },
  { name: 'The Whole Truth', key: 'thewholetruth', category: 'Healthy food', hero: '/pitch/thewholetruth-hero.png', life: '/pitch/thewholetruth-life.png', video: '/pitch/ugc-food.mp4' },
  { name: 'Snitch', key: 'snitch', category: 'Mens fashion', hero: '/pitch/snitch-hero.png', life: '/pitch/snitch-life.png', video: '/pitch/ugc-fashion.mp4' },
  { name: 'SuperBottoms', key: 'superbottoms', category: 'Baby care', hero: '/pitch/superbottoms-hero.png', life: '/pitch/superbottoms-life.png' },
  { name: 'Pilgrim', key: 'pilgrim', category: 'Beauty', hero: '/pitch/pilgrim-hero.png', life: '/pitch/pilgrim-life.png' },
  { name: 'Wakao Foods', key: 'wakao', category: 'Plant-based food', hero: '/pitch/wakao-hero.png', life: '/pitch/wakao-life.png' },
  { name: 'The Sleep Company', key: 'sleepcompany', category: 'Home & sleep', hero: '/pitch/sleepcompany-hero.png', life: '/pitch/sleepcompany-life.png' },
]

// Generated UGC videos (Sora-2 / Veo-3) for the video showcase.
export const GENERATED_VIDEOS = [
  { src: '/pitch/ugc-skincare.mp4', label: 'Skincare UGC', tag: 'Beauty' },
  { src: '/pitch/ugc-food.mp4', label: 'Protein bar UGC', tag: 'Food' },
  { src: '/pitch/ugc-fashion.mp4', label: 'Fashion UGC', tag: 'Apparel' },
]

// Branded product creatives generated by ArrowLabs (gpt-image-2).
export const BRAND_CREATIVES = [
  { src: '/marketing/brands/cerave.png', brand: 'CeraVe', type: 'Main Image' },
  { src: '/marketing/brands/owala.png', brand: 'Owala', type: 'Product Photo' },
  { src: '/marketing/brands/sony.png', brand: 'Sony', type: 'Hero Shot' },
  { src: '/marketing/brands/prime.png', brand: 'PRIME', type: 'Ad Creative' },
  { src: '/marketing/brands/gymshark.png', brand: 'Gymshark', type: 'Ad Creative' },
  { src: '/marketing/brands/ninja.png', brand: 'Ninja', type: 'Lifestyle' },
]
