import type { Metadata } from 'next'
import { PageHeader } from '@/components/site/page-header'
import { Workspace } from '@/components/site/workspace'
import { Process } from '@/components/site/process'
import { Architecture } from '@/components/site/architecture'
import { UseCases } from '@/components/site/use-cases'
import { Comparison } from '@/components/site/comparison'
import { CTA } from '@/components/site/cta'

export const metadata: Metadata = {
  title: 'Features',
  description:
    'One workspace for every creative your store needs: listings, ads, product photography, and UGC video, generated by AI and directed by you.',
  alternates: { canonical: '/features' },
  openGraph: {
    title: 'Features · ArrowLabs',
    description: 'One workspace for listings, ads, product photography, and UGC video.',
    url: '/features',
    images: [{ url: '/opengraph-image', width: 1200, height: 630, alt: 'ArrowLabs' }],
  },
  twitter: { images: ['/opengraph-image'] },
}

export default function FeaturesPage() {
  return (
    <>
      <PageHeader
        eyebrow="§ Features"
        title="One workspace,"
        accent="every creative."
        description="Paste a product link and ArrowLabs runs the full pipeline, from brand brain to listing images, ad angles, studio photography, and UGC video. Here is how the studio works end to end."
      />
      <Workspace />
      <Process />
      <Architecture />
      <UseCases />
      <Comparison />
      <CTA />
    </>
  )
}
