'use client'

import { motion } from 'framer-motion'
import { MARKETING } from '@/lib/images'
import { BRAND_CREATIVES } from '@/lib/showcase'

const TILES = [
  { src: MARKETING.aplusLifestyle, label: 'A+ Lifestyle Module', lab: 'ListingLab', span: 'sm:col-span-2 sm:row-span-2', ratio: 'aspect-[3/2]' },
  { src: MARKETING.amazonListing, label: 'Main Image', lab: 'ListingLab', span: '', ratio: 'aspect-square' },
  { src: MARKETING.adCreative, label: 'Ad Creative', lab: 'AngleLab', span: 'sm:row-span-2', ratio: 'aspect-[2/3]' },
  { src: MARKETING.ugcCreator, label: 'UGC Frame', lab: 'VideoLab', span: 'sm:row-span-2', ratio: 'aspect-[2/3]' },
  { src: '/marketing/premium/lifestyle-kitchen.png', label: 'Lifestyle Scene', lab: 'PhotoLab', span: 'sm:col-span-2', ratio: 'aspect-[3/2]' },
]

export function Showcase() {
  return (
    <section id="showcase" className="relative overflow-hidden py-24 lg:py-32">
      <div className="mx-auto max-w-[1280px] px-6 lg:px-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          className="max-w-2xl"
        >
          <span className="label-mono text-accent">Real output · generated by ThreeArrow AI</span>
          <h2 className="mt-4 font-display text-[38px] font-light leading-[1.05] tracking-tight sm:text-[52px]">
            A+ content, ad creative, and product photography,{' '}
            <span className="font-display-italic text-gradient">rendered on demand.</span>
          </h2>
          <p className="mt-5 text-base leading-relaxed text-muted-foreground">
            Every image below was generated inside ArrowLabs from a single JSON prompt. No stock, no
            photographer, no reshoots. This is the actual quality your store gets from day one.
          </p>
        </motion.div>

        <div className="mt-14 grid auto-rows-[180px] grid-cols-2 gap-4 sm:auto-rows-[200px] sm:grid-cols-4 lg:gap-5">
          {TILES.map((t, i) => (
            <motion.figure
              key={t.label}
              initial={{ opacity: 0, y: 28, scale: 0.98 }}
              whileInView={{ opacity: 1, y: 0, scale: 1 }}
              viewport={{ once: true, margin: '-60px' }}
              transition={{ duration: 0.65, delay: i * 0.08, ease: [0.22, 1, 0.36, 1] }}
              whileHover={{ y: -6 }}
              className={`group relative overflow-hidden rounded-2xl border border-border/60 bg-muted ${t.span}`}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img
                src={t.src}
                alt={t.label}
                className="h-full w-full object-cover transition-transform duration-700 ease-out group-hover:scale-105"
                loading="lazy"
              />
              <div className="pointer-events-none absolute inset-0 bg-gradient-to-t from-black/55 via-black/0 to-black/0 opacity-90" />
              <figcaption className="absolute inset-x-0 bottom-0 flex items-center justify-between p-4">
                <span className="text-sm font-medium text-white drop-shadow">{t.label}</span>
                <span className="label-mono rounded-full bg-white/15 px-2 py-0.5 text-[10px] text-white backdrop-blur">
                  {t.lab}
                </span>
              </figcaption>
            </motion.figure>
          ))}
        </div>

        {/* Branded product creatives - generated on real brands */}
        <div className="mt-6">
          <p className="label-mono text-xs text-muted-foreground">Branded product shots, generated from a name + a prompt</p>
          <div className="mt-4 grid grid-cols-3 gap-3 sm:grid-cols-6">
            {BRAND_CREATIVES.map((b, i) => (
              <motion.div
                key={b.brand}
                initial={{ opacity: 0, y: 16 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.5, delay: i * 0.06 }}
                whileHover={{ y: -5 }}
                className="group relative overflow-hidden rounded-xl border border-border/60 bg-muted"
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img src={b.src} alt={b.brand} loading="lazy" className="aspect-square w-full object-cover transition-transform duration-500 group-hover:scale-105" />
                <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/60 to-transparent p-2">
                  <span className="text-[11px] font-medium text-white">{b.brand}</span>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="mt-10 flex flex-col items-start gap-4 sm:flex-row sm:items-center"
        >
          <a
            href="/login"
            className="group inline-flex items-center gap-2 rounded-full btn-gradient px-7 py-3.5 text-sm font-semibold"
          >
            Generate yours free
            <span className="transition-transform group-hover:translate-x-0.5">→</span>
          </a>
          <span className="text-sm text-muted-foreground">7 days completely free · unlimited · no card</span>
        </motion.div>
      </div>
    </section>
  )
}
