import { NextRequest } from 'next/server'
import { ok, requireActor, wrapError } from '@/lib/api'
import { db } from '@/lib/db'

// GET: every asset generated by the actor's org, newest first, with its ASIN.
export async function GET(req: NextRequest) {
  const res = await requireActor(req)
  if ('error' in res) return res.error
  try {
    const where = res.actor.orgId
      ? { campaign: { orgId: res.actor.orgId } }
      : { campaign: { userId: res.actor.userId } }
    const assets = await db.asset.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: 500,
      select: {
        id: true, type: true, lab: true, imageUrl: true, videoUrl: true, status: true, createdAt: true,
        campaignId: true,
        campaign: { select: { asin: true, productName: true } },
      },
    })
    return ok(assets, { count: assets.length })
  } catch (err) {
    return wrapError('api.assets', err)
  }
}
