"""
ArrowLabs scraper service.
Uses curl_cffi (Chrome TLS impersonation) to bypass Amazon's bot-wall from a
datacenter IP, then parses product data, reviews, and competitor search results.
Runs locally on the VM; the Next.js app calls it as the primary Amazon provider.

Endpoints:
  GET /health
  GET /product?asin=ASIN&domain=amazon.com   -> product + embedded top reviews
  GET /reviews?asin=ASIN&domain=amazon.com&pages=2  -> deeper reviews
  GET /search?q=keyword&domain=amazon.com&limit=10  -> competitor listings
"""

import os
import re
import time
import random
import threading
from urllib.parse import quote
from flask import Flask, request, jsonify
from curl_cffi import requests as cr
from bs4 import BeautifulSoup
import marketplaces

app = Flask(__name__)
HERE = os.path.dirname(os.path.abspath(__file__))

# Optional logged-in Amazon session (cookies) generated by login.py. When present,
# Playwright reuses it so review TEXT (which Amazon gates behind sign-in) is scraped.
STATE_FILE = os.path.join(HERE, "amazon_state.json")

IMPERSONATE = "safari17_0"
# Amazon captcha-walls the chrome12x TLS fingerprints from some IPs (returns a 5KB
# robot-check page) while letting Safari / chrome131 through with the full page.
# Lead with the confirmed-good profiles so the direct fetch lands the real page first.
PROFILES = ["safari17_0", "chrome131", "safari15_5", "chrome124"]
TIMEOUT = 15
HEADERS = {
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
    "Accept-Language": "en-US,en;q=0.9",
}

# Amazon blocks some datacenter IP ranges per-region (e.g. amazon.com returns a
# bot "dogs of amazon" 404 to an India-hosted VM even for valid ASINs), while the
# local marketplace (amazon.in) serves fine. If the requested marketplace is
# blocked/not-found we look up the product on these reachable fallbacks instead,
# so a valid ASIN never fails just because one storefront blocks this host.
# Override with SCRAPER_FALLBACK_DOMAINS="amazon.in,amazon.com,...".
FALLBACK_DOMAINS = [
    d.strip()
    for d in os.environ.get("SCRAPER_FALLBACK_DOMAINS", "amazon.in,amazon.com").split(",")
    if d.strip()
]


# ---------------- proxy pool (rotation + health) ----------------
def _normalize_proxy(line: str):
    line = line.strip()
    if not line or line.startswith("#"):
        return None
    if line.startswith("http://") or line.startswith("https://"):
        return line
    parts = line.split(":")
    if len(parts) == 4:  # ip:port:user:pass
        ip, port, user, pw = parts
        return f"http://{user}:{pw}@{ip}:{port}"
    if len(parts) == 2:  # ip:port
        return f"http://{parts[0]}:{parts[1]}"
    return None


def _load_proxies():
    proxies = []
    raw = os.environ.get("SCRAPER_PROXIES", "")
    for line in raw.split(","):
        p = _normalize_proxy(line)
        if p:
            proxies.append(p)
    pf = os.path.join(HERE, "proxies.txt")
    if os.path.exists(pf):
        with open(pf) as f:
            for line in f:
                p = _normalize_proxy(line)
                if p:
                    proxies.append(p)
    return list(dict.fromkeys(proxies))  # de-dupe, keep order


class ProxyPool:
    """Thread-safe rotating pool with per-proxy cooldown after failures."""

    def __init__(self, proxies):
        self.proxies = proxies
        self.lock = threading.Lock()
        self.cooldown = {}  # proxy -> epoch until which it's benched
        self.idx = 0

    def get(self):
        with self.lock:
            if not self.proxies:
                return None
            now = time.time()
            for _ in range(len(self.proxies)):
                p = self.proxies[self.idx % len(self.proxies)]
                self.idx += 1
                if self.cooldown.get(p, 0) <= now:
                    return p
            return None  # all benched -> go direct

    def penalize(self, proxy, seconds=120):
        if proxy:
            with self.lock:
                self.cooldown[proxy] = time.time() + seconds

    def count(self):
        return len(self.proxies)


POOL = ProxyPool(_load_proxies())

# --- result cache + browser concurrency limit (scale hardening) ---
# Dedupe repeated scrapes: if 500 users audit the same popular ASIN, we scrape it
# once per TTL instead of 500 times. Bounded, thread-safe, in-memory.
_CACHE = {}
_CACHE_LOCK = threading.Lock()


def cache_get(key, ttl):
    with _CACHE_LOCK:
        v = _CACHE.get(key)
        if v and (time.time() - v[0]) < ttl:
            return v[1]
    return None


def cache_set(key, val):
    with _CACHE_LOCK:
        _CACHE[key] = (time.time(), val)
        if len(_CACHE) > 800:
            oldest = min(_CACHE.items(), key=lambda kv: kv[1][0])[0]
            _CACHE.pop(oldest, None)


# Cap concurrent headless-Chromium renders so a spike of review requests can't
# exhaust the VM's memory. Extra requests queue for a slot.
_BROWSER_SEM = threading.Semaphore(2)


def fetch(url: str, retries: int = 2):
    """DIRECT-FIRST fetch: Amazon serves product/search pages fine to the VM's IP
    directly, and it's fast (~2s). Proxies are a FALLBACK for when a direct hit is
    blocked/rate-limited (e.g. under bulk). This keeps latency low so the app never
    times out into demo data."""
    last = None
    # 1) direct (fast, reliable for product/search)
    for i in range(2):
        try:
            resp = cr.get(url, impersonate=PROFILES[i % len(PROFILES)], timeout=TIMEOUT, headers=HEADERS)
            if resp.status_code not in (403, 429, 503):
                return resp.status_code, resp.text
            last = RuntimeError(f"http_{resp.status_code}")
        except Exception as e:
            last = e
    # 2) proxy fallback (only if direct got blocked)
    for i in range(retries):
        proxy = POOL.get()
        if not proxy:
            break
        try:
            resp = cr.get(url, impersonate=PROFILES[i % len(PROFILES)], timeout=TIMEOUT, headers=HEADERS, proxies={"http": proxy, "https": proxy})
            if resp.status_code in (403, 429, 503):
                POOL.penalize(proxy)
                last = RuntimeError(f"http_{resp.status_code}")
                continue
            return resp.status_code, resp.text
        except Exception as e:
            POOL.penalize(proxy)
            last = e
    raise last or RuntimeError("fetch failed")


def warmed_fetch(url: str, domain: str):
    """Cookie-warmed session behind a rotating proxy: hit the homepage first to
    harvest session cookies (Amazon serves more inline data to warmed sessions),
    then fetch the target. Falls back to plain fetch on any failure."""
    for i in range(3):
        proxy = POOL.get()
        try:
            s = cr.Session(impersonate=PROFILES[i % len(PROFILES)], headers=HEADERS)
            if proxy:
                s.proxies = {"http": proxy, "https": proxy}
            try:
                s.get(f"https://www.{domain}/", timeout=TIMEOUT)  # warm cookies
            except Exception:
                pass
            resp = s.get(url, timeout=TIMEOUT)
            if resp.status_code in (403, 429, 503):
                POOL.penalize(proxy)
                continue
            return resp.status_code, resp.text
        except Exception:
            POOL.penalize(proxy)
    return fetch(url)


def txt(el):
    return el.get_text(strip=True) if el else ""


def is_botwall(html: str) -> bool:
    return bool(
        re.search(
            r"Robot Check|Enter the characters you see|Type the characters|"
            r"To discuss automated access|automated access to Amazon data|"
            r"/errors/validateCaptcha|api-services-support@amazon",
            html,
            re.I,
        )
        and 'id="productTitle"' not in html
    )


def is_not_found(html: str) -> bool:
    # Amazon's not-found / invalid-ASIN pages. Catch these so a garbage ASIN fails
    # cleanly instead of us parsing a stray product off a fallback page.
    return bool(
        re.search(
            r"Sorry! We couldn'?t find that page|we couldn'?t find that page|Looking for something\?|"
            r"not a functioning page|Page Not Found|dogs-of-amazon|The Web address you entered is not",
            html,
            re.I,
        )
        and 'id="productTitle"' not in html
    )


_CURRENCY = {
    "amazon.com": "USD", "amazon.in": "INR", "amazon.co.uk": "GBP", "amazon.ca": "CAD",
    "amazon.de": "EUR", "amazon.fr": "EUR", "amazon.it": "EUR", "amazon.es": "EUR",
    "amazon.co.jp": "JPY", "amazon.com.au": "AUD", "amazon.com.mx": "MXN",
}


def currency_for(domain: str) -> str:
    return _CURRENCY.get(domain, "USD")


def unescape_html(html: str) -> str:
    # Amazon embeds reviews / search cards as JSON-escaped HTML in <script> blocks.
    # Normalizing the escapes surfaces them to the DOM parser.
    return (
        html.replace('\\"', '"')
        .replace("\\/", "/")
        .replace("\\u003c", "<")
        .replace("\\u003e", ">")
        .replace("\\u0026", "&")
        .replace("\\n", " ")
    )


# ---------------- product ----------------
def parse_product(html: str, asin: str, domain: str):
    soup = BeautifulSoup(html, "lxml")

    # Title: #productTitle first, then robust fallbacks (og:title / <title>) so a
    # slightly different page layout never returns "noparse" for a real product.
    def _good(t):
        t = (t or "").strip()
        return t if len(t) >= 8 and not re.match(r"^amazon\.\w+$", t, re.I) and "robot" not in t.lower() else ""

    title = _good(txt(soup.select_one("#productTitle")))
    if not title:
        og = soup.select_one('meta[property="og:title"]')
        title = _good(og["content"]) if (og and og.get("content")) else ""
    if not title:
        tt = soup.select_one("title")
        if tt:
            t = txt(tt)
            # "Buy <name> Online at Low Prices in India - Amazon.in" / "<name>: Amazon.in"
            t = re.sub(r"^Buy\s+", "", t, flags=re.I)
            t = re.split(r"\s*(Online at Low Prices|:\s*Amazon|\|\s*Amazon|-\s*Amazon)", t, 1)[0]
            title = _good(t)

    brand = ""
    byline = soup.select_one("#bylineInfo")
    if byline:
        brand = re.sub(r"^(Visit the |Brand: )", "", txt(byline))
        brand = re.sub(r"'s? Store$| Store$", "", brand).strip()

    def price_from(sel):
        el = soup.select_one(sel)
        if el:
            m = re.search(r"[\d,]+\.?\d*", txt(el))
            if m:
                return float(m.group(0).replace(",", ""))
        return 0.0

    price = (
        price_from("#corePrice_feature_div .a-offscreen")
        or price_from("#corePriceDisplay_desktop_feature_div .a-offscreen")
        or price_from("#apex_desktop .a-offscreen")
        or price_from("span.a-price .a-offscreen")
    )
    if not price:
        # buy box can be hidden by delivery-location; price is still in the page JSON
        m = re.search(r'"priceAmount"\s*:\s*([\d.]+)', html) or re.search(
            r'"displayPrice"\s*:\s*"[^\d]*([\d,.]+)"', html
        )
        if m:
            price = float(m.group(1).replace(",", ""))
    list_price = price_from(".basisPrice .a-offscreen") or price_from("span.a-price.a-text-price .a-offscreen")

    rating = 0.0
    rt = soup.select_one("#acrPopover")
    if rt and rt.get("title"):
        m = re.search(r"([\d.]+)", rt["title"])
        if m:
            rating = float(m.group(1))
    if not rating:
        m = re.search(r"([\d.]+)\s*out of\s*5", html)
        rating = float(m.group(1)) if m else 0.0

    review_count = 0
    rc = soup.select_one("#acrCustomerReviewText")
    if rc:
        m = re.search(r"([\d,]+)", txt(rc))
        review_count = int(m.group(1).replace(",", "")) if m else 0

    bullets = [txt(li) for li in soup.select("#feature-bullets li span.a-list-item") if txt(li)]
    if not bullets:
        bullets = [txt(li) for li in soup.select("#feature-bullets li") if txt(li)]

    description = txt(soup.select_one("#productDescription")) or txt(soup.select_one("#bookDescription_feature_div"))

    # hi-res images from the image-block JSON
    images = re.findall(r'"hiRes":"([^"]+\.jpg)"', html)
    if not images:
        images = re.findall(r'"large":"([^"]+\.jpg)"', html)
    seen = set()
    images = [i for i in images if not (i in seen or seen.add(i))][:10]

    # category / BSR
    category = ""
    m = re.search(r"in\s+([A-Za-z &,]+)\s*\(See Top 100", html)
    if m:
        category = m.group(1).strip()

    reviews = parse_reviews(soup)
    if not reviews:
        reviews = parse_reviews(BeautifulSoup(unescape_html(html), "lxml"))

    return {
        "asin": asin,
        "title": title,
        "brand": brand,
        "price": price,
        "listPrice": list_price or None,
        "currency": currency_for(domain),
        "rating": rating,
        "reviewCount": review_count,
        "category": category,
        "features": bullets,
        "bullets": bullets,
        "description": description,
        "images": images,
        "variants": [],
        "availability": txt(soup.select_one("#availability")) or "unknown",
        "marketplace": domain,
        "reviews": reviews,
    }


# ---------------- reviews ----------------
def parse_reviews(soup):
    out = []
    for rv in soup.select('div[data-hook="review"], li[data-hook="review"]'):
        rating = 0
        star = rv.select_one('[data-hook="review-star-rating"] .a-icon-alt, [data-hook="cmps-review-star-rating"] .a-icon-alt, i.review-rating .a-icon-alt')
        if star:
            m = re.search(r"([\d.]+)", txt(star))
            rating = int(float(m.group(1))) if m else 0
        title_el = rv.select_one('[data-hook="review-title"]')
        title = ""
        if title_el:
            spans = title_el.select("span")
            title = txt(spans[-1]) if spans else txt(title_el)
        body = txt(rv.select_one('[data-hook="review-body"]'))
        author = txt(rv.select_one(".a-profile-name"))
        date_el = txt(rv.select_one('[data-hook="review-date"]'))
        verified = bool(rv.select_one('[data-hook="avp-badge"]'))
        helpful = 0
        h = rv.select_one('[data-hook="helpful-vote-statement"]')
        if h:
            m = re.search(r"([\d,]+)", txt(h))
            helpful = int(m.group(1).replace(",", "")) if m else 0
        if body or title:
            out.append({
                "author": author or "Anonymous",
                "rating": rating or 5,
                "title": title,
                "body": body,
                "date": date_el,
                "verified": verified,
                "helpful": helpful,
            })
    return out


def fetch_reviews_pages(asin: str, domain: str, pages: int):
    all_reviews = []
    for page in range(1, pages + 1):
        url = f"https://www.{domain}/product-reviews/{asin}/?sortBy=recent&pageNumber={page}&reviewerType=all_reviews"
        try:
            code, html = fetch(url)
            if code != 200 or is_botwall(html):
                break
            revs = parse_reviews(BeautifulSoup(html, "lxml"))
            if not revs:
                revs = parse_reviews(BeautifulSoup(unescape_html(html), "lxml"))
            if not revs:
                break
            all_reviews.extend(revs)
        except Exception:
            break
    return all_reviews


# Reviews are JS/AJAX-rendered on Amazon, so curl_cffi can't see them. Playwright
# (headless Chromium) renders the page like a real browser and surfaces them.
def render_reviews(asin: str, domain: str, max_reviews: int = 20):
    try:
        from playwright.sync_api import sync_playwright
    except Exception:
        return []
    out = []
    urls = [
        f"https://www.{domain}/product-reviews/{asin}/?sortBy=recent&reviewerType=all_reviews",
        f"https://www.{domain}/dp/{asin}",
    ]
    # cap concurrent chromium renders (queue up to 40s for a free slot)
    if not _BROWSER_SEM.acquire(timeout=40):
        return []  # too busy; skip gracefully rather than pile up and OOM
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(
                headless=True, args=["--no-sandbox", "--disable-dev-shm-usage", "--disable-gpu"]
            )
            ctx_kwargs = dict(
                user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
                locale="en-US",
                viewport={"width": 1280, "height": 2000},
            )
            if os.path.exists(STATE_FILE):
                ctx_kwargs["storage_state"] = STATE_FILE  # logged-in session -> full reviews
            ctx = browser.new_context(**ctx_kwargs)
            page = ctx.new_page()
            for url in urls:
                try:
                    page.goto(url, timeout=30000, wait_until="domcontentloaded")
                    try:
                        page.wait_for_selector('[data-hook="review"]', timeout=9000)
                    except Exception:
                        pass
                    html = page.content()
                    revs = parse_reviews(BeautifulSoup(html, "lxml"))
                    if revs:
                        out = revs
                        break
                except Exception:
                    continue
            browser.close()
    except Exception:
        return []
    finally:
        _BROWSER_SEM.release()
    return out[:max_reviews]


# ---------------- search / competitors ----------------
def parse_search(html: str, domain: str, limit: int):
    soup = BeautifulSoup(html, "lxml")
    out = []
    cards = soup.select('div[data-component-type="s-search-result"]')
    pos = 0
    for card in cards:
        asin = card.get("data-asin", "")
        if not asin:
            continue
        title = txt(card.select_one("h2 span")) or txt(card.select_one("h2 a span")) or txt(card.select_one("h2"))
        if not title:
            continue
        pos += 1
        # price: first a-price a-offscreen only (avoid range concatenation)
        price = 0.0
        pe = card.select_one("span.a-price span.a-offscreen")
        if pe:
            m = re.search(r"[\d,]+\.?\d*", txt(pe))
            price = float(m.group(0).replace(",", "")) if m else 0.0
        # rating: prefer aria-label "X out of 5 stars"
        rating = 0.0
        ra = card.select_one('[aria-label*="out of 5 stars"]')
        if ra:
            m = re.search(r"([\d.]+)\s*out of", ra.get("aria-label", ""))
            rating = float(m.group(1)) if m else 0.0
        if not rating:
            ri = card.select_one("i.a-icon-star-small .a-icon-alt, i.a-icon-star .a-icon-alt")
            if ri:
                m = re.search(r"([\d.]+)", txt(ri))
                rating = float(m.group(1)) if m else 0.0
        # review count: the ratings-count link (aria-label ends with 'ratings')
        review_count = 0
        rc = card.select_one('a[aria-label$="ratings"], a[aria-label$="rating"]')
        if rc and rc.get("aria-label"):
            m = re.search(r"([\d,]+)", rc["aria-label"])
            review_count = int(m.group(1).replace(",", "")) if m else 0
        if not review_count:
            rc2 = card.select_one("span.a-size-base.s-underline-text")
            if rc2:
                m = re.search(r"([\d,]+)", txt(rc2))
                review_count = int(m.group(1).replace(",", "")) if m else 0
        thumb = ""
        img = card.select_one("img.s-image")
        if img:
            thumb = img.get("src", "")
        block = str(card)
        out.append({
            "asin": asin,
            "title": title,
            "brand": "",
            "price": price,
            "rating": rating,
            "reviewCount": review_count,
            "thumbnail": thumb,
            "sponsored": "Sponsored" in block,
            "bestSeller": bool(re.search(r"Best Seller", block, re.I)),
            "amazonChoice": bool(re.search(r"Amazon'?s\s*Choice", block, re.I)),
            "position": pos,
            "url": f"https://www.{domain}/dp/{asin}",
        })
        if len(out) >= limit:
            break
    return out


# ---------------- routes ----------------
@app.get("/health")
def health():
    return jsonify({"ok": True, "impersonate": IMPERSONATE, "proxies": POOL.count(), "session": os.path.exists(STATE_FILE), "marketplaces": list(marketplaces.PLATFORMS.keys()) + ["amazon"]})


@app.get("/scrape")
def scrape():
    """Unified multi-marketplace scrape: Flipkart, Myntra, Noon, Namshi, Nykaa.
    Amazon keeps its dedicated /product route (ASIN + review session)."""
    platform = request.args.get("platform", "").strip().lower()
    pid = request.args.get("id", "").strip()
    region = request.args.get("region", "").strip() or None
    if not platform or not pid:
        return jsonify({"error": "missing platform or id"}), 400
    if platform == "amazon":
        return jsonify({"error": "use /product for amazon"}), 400
    if platform not in marketplaces.PLATFORMS:
        return jsonify({"error": f"unsupported platform {platform}"}), 400

    ck = f"scrape:{platform}:{region}:{pid}"
    cached = cache_get(ck, 600)
    if cached is not None:
        return jsonify(cached)

    url = marketplaces.build_url(platform, pid, region)
    try:
        code, html = fetch(url)
    except Exception as e:
        return jsonify({"error": f"fetch failed: {str(e)[:80]}"}), 502
    if code != 200 or is_botwall(html) or len(html) < 3000:
        return jsonify({"error": f"not found or blocked (HTTP {code})", "url": url}), 404
    data = marketplaces.normalize(platform, html, url)
    if not data.get("title"):
        return jsonify({"error": "no product parsed", "url": url}), 502
    cache_set(ck, data)
    return jsonify(data)


@app.get("/product")
def product():
    asin = request.args.get("asin", "").strip()
    domain = request.args.get("domain", "amazon.com").strip()
    if not asin:
        return jsonify({"error": "missing asin"}), 400
    ck = f"product:{domain}:{asin.upper()}"
    cached = cache_get(ck, 600)
    if cached is not None:
        return jsonify(cached)
    # Try the requested marketplace first, then reachable fallbacks. A direct hit
    # that's blocked returns fast (~2s), so the fallback loop stays well within the
    # app's timeout while still finding the product wherever it actually lives.
    try_domains = [domain] + [d for d in FALLBACK_DOMAINS if d != domain]
    tried = []
    for dom in try_domains:
        url = f"https://www.{dom}/dp/{asin}"
        # Amazon intermittently serves a bot-lite page (200 but no product data) even
        # from residential IPs. A plain retry, then a cookie-warmed session, almost
        # always gets the full page, so we don't give up on the first "noparse".
        data = None
        for attempt in range(4):
            try:
                code, html = (fetch(url) if attempt < 2 else warmed_fetch(url, dom))
            except Exception as e:
                last_err = f"{dom}=err:{str(e)[:30]}"
                time.sleep(1.2)
                continue
            if is_not_found(html):
                last_err = f"{dom}=404"
                break  # genuinely missing on this domain; move to fallback domain
            if code != 200 or is_botwall(html) or len(html) < 5000:
                last_err = f"{dom}={code}/lite"
                time.sleep(1.2)
                continue
            parsed = parse_product(html, asin, dom)
            if not parsed.get("title"):
                last_err = f"{dom}=noparse"
                time.sleep(1.2)
                continue
            data = parsed
            break
        if data:
            data["marketplace"] = dom
            cache_set(f"product:{dom}:{asin.upper()}", data)
            cache_set(ck, data)
            return jsonify(data)
        tried.append(last_err)
    return jsonify({"error": f"not found or blocked (tried {', '.join(tried)})"}), 404


@app.get("/reviews")
def reviews():
    asin = request.args.get("asin", "").strip()
    domain = request.args.get("domain", "amazon.com").strip()
    pages = min(int(request.args.get("pages", "2")), 5)
    if not asin:
        return jsonify({"error": "missing asin"}), 400
    ck = f"reviews:{domain}:{asin.upper()}"
    cached = cache_get(ck, 1800)  # reviews change slowly; 30 min
    if cached is not None:
        return jsonify(cached)
    try:
        # Playwright (rendered) is the reliable path; curl_cffi pages as fallback.
        reviews = render_reviews(asin, domain)
        if not reviews:
            reviews = fetch_reviews_pages(asin, domain, pages)
        result = {"reviews": reviews, "rendered": bool(reviews)}
        if reviews:
            cache_set(ck, result)
        return jsonify(result)
    except Exception as e:
        return jsonify({"error": str(e)}), 502


@app.get("/search")
def search():
    q = request.args.get("q", "").strip()
    domain = request.args.get("domain", "amazon.com").strip()
    limit = min(int(request.args.get("limit", "10")), 20)
    if not q:
        return jsonify({"error": "missing q"}), 400
    ck = f"search:{domain}:{q.lower()}:{limit}"
    cached = cache_get(ck, 600)
    if cached is not None:
        return jsonify(cached)
    try:
        code, html = fetch(f"https://www.{domain}/s?k={quote(q)}")
        if code != 200:
            return jsonify({"error": f"blocked (HTTP {code})"}), 502
        results = parse_search(html, domain, limit)
        if not results:
            results = parse_search(unescape_html(html), domain, limit)
        if not results:
            return jsonify({"error": "no results parsed"}), 502
        out = {"results": results}
        cache_set(ck, out)
        return jsonify(out)
    except Exception as e:
        return jsonify({"error": str(e)}), 502


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8071)
